# Generated by Django 4.0.6 on 2022-07-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_job_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Widget',
        ),
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
